rbac/controllers/AuthAssignmentController.php
<?php

namespace reseed\rbac\controllers;

use Yii;
use reseed\rbac\models\AuthAssignment;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuthAssignmentController implements the CRUD actions for AuthAssignment model.
 */
class AuthAssignmentController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all AuthAssignment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => AuthAssignment::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AuthAssignment model.
     * @param string $item_name
     * @param string $user_id
     * @return mixed
     */
    public function actionView($item_name, $user_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($item_name, $user_id),
        ]);
    }

    /**
     * Creates a new AuthAssignment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AuthAssignment();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'item_name' => $model->item_name, 'user_id' => $model->user_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing AuthAssignment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $item_name
     * @param string $user_id
     * @return mixed
     */
    public function actionUpdate($item_name, $user_id)
    {
        $model = $this->findModel($item_name, $user_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'item_name' => $model->item_name, 'user_id' => $model->user_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AuthAssignment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $item_name
     * @param string $user_id
     * @return mixed
     */
    public function actionDelete($item_name, $user_id)
    {
        $this->findModel($item_name, $user_id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuthAssignment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $item_name
     * @param string $user_id
     * @return AuthAssignment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($item_name, $user_id)
    {
        if (($model = AuthAssignment::findOne(['item_name' => $item_name, 'user_id' => $user_id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

rbac/controllers/AuthItemChildController.php
<?php

namespace reseed\rbac\controllers;

use Yii;
use reseed\rbac\models\AuthItemChild;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\helpers\ArrayHelper;

/**
 * AuthItemChildController implements the CRUD actions for AuthItemChild model.
 */
class AuthItemChildController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all AuthItemChild models.
     * @return mixed
     */
    public function actionIndex()
    {
        //process editable
        $response = $this->processAuthItemEditable();
        if ($response) {
//            $this->refresh();
            return $response;
        }
        
        $dataProvider = new ActiveDataProvider([
            'query' => AuthItemChild::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AuthItemChild model.
     * @param string $parent
     * @param string $child
     * @return mixed
     */
    public function actionView($parent, $child)
    {
        return $this->render('view', [
            'model' => $this->findModel($parent, $child),
        ]);
    }

    /**
     * Creates a new AuthItemChild model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AuthItemChild();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'parent' => $model->parent, 'child' => $model->child]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing AuthItemChild model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $parent
     * @param string $child
     * @return mixed
     */
    public function actionUpdate($parent, $child)
    {
        $model = $this->findModel($parent, $child);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'parent' => $model->parent, 'child' => $model->child]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AuthItemChild model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $parent
     * @param string $child
     * @return mixed
     */
    public function actionDelete($parent, $child)
    {
        $this->findModel($parent, $child)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuthItemChild model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $parent
     * @param string $child
     * @return AuthItemChild the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($parent, $child)
    {
        if (($model = AuthItemChild::findOne(['parent' => $parent, 'child' => $child])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
     * Update attribute value in model.
     * @return json
     */
    private function processAuthItemEditable()
    {
        if (Yii::$app->request->post('hasEditable')) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            
            $data = unserialize(Yii::$app->request->post('editableKey'));
            $model = AuthItemChild::findOne([
                'parent' => ArrayHelper::getValue($data, 'parent'),
                'child' => ArrayHelper::getValue($data, 'child')
            ]);
//var_dump(Yii::$app->request->post());die();
            $response = ['output' => '', 'message' => ''];
            
            $option = current(Yii::$app->request->post($model->formName()));
            
            if ($model->load($option, '') && $model->save()) {
                $response['output'] = reset($option);
            } else {
                $response['message'] = $model->getFirstError(key($model->dirtyAttributes[0]));
            }

            return $response;
        }

        return null;
    }
}

rbac/controllers/AuthItemController.php
<?php

namespace reseed\rbac\controllers;

use Yii;
use reseed\rbac\models\AuthItem;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuthItemController implements the CRUD actions for AuthItem model.
 */
class AuthItemController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all AuthItem models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => AuthItem::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AuthItem model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AuthItem model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AuthItem();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing AuthItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AuthItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuthItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return AuthItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AuthItem::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

rbac/controllers/AuthRuleController.php
<?php

namespace reseed\rbac\controllers;

use Yii;
use reseed\rbac\models\AuthRule;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuthRuleController implements the CRUD actions for AuthRule model.
 */
class AuthRuleController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all AuthRule models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => AuthRule::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AuthRule model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AuthRule model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AuthRule();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing AuthRule model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AuthRule model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuthRule model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return AuthRule the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AuthRule::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

rbac/controllers/DefaultController.php
<?php

namespace reseed\rbac\controllers;

use reseed\rbac\models\PermissionsTableForm;
use yii\base\DynamicModel;
use yii\web\Controller;

class DefaultController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionTable()
    {
        $model = new PermissionsTableForm();
        $model->setAuthManager(\Yii::$app->authManager);

        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return $this->refresh();
        }

        $roles = \Yii::$app->authManager->getRoles();
        $permissions = \Yii::$app->authManager->getPermissions();

        return $this->render('table', [
            'allRoles' => $roles,
            'allPermissions' => $permissions,
            'model' => $model
        ]);
    }
}

rbac/views/default/_tableDetails.php
<?php

use yii\helpers\Html;

$currentPermissions = $model['permissions'];
$currentPermissions = reset($currentPermissions);
$currentPermissions = array_keys($currentPermissions);

?>

<table id="permissions-table" class="table table-bordered">
    <tr>
        <td>Permissions</td>
        <td colspan="<?= count($allRoles) ?>" style="text-align: center">allRoles</td>
    </tr>
    <tr>
        <td></td>
        <?php foreach ($allRoles as $role): ?>
            <td>
                <?= Html::checkbox('', null, [
                    'label' => $role->name,
                    'class' => 'checker',
                    'data' => [
                        'role' => $role->name,
                        'group' => $model['groupName']
                    ]
                ]
                ) ?>

            </td>
        <?php endforeach; ?>
    </tr>
    <?php foreach ($currentPermissions as $permission): ?>
    <tr>
        <td><?= $allPermissions[$permission]->name ?>
        <p class="permission-description"><?= $allPermissions[$permission]->description ?></p>
        </td>
        <?php foreach ($allRoles as $role): ?>
            <td style="background-color: <?= empty($model['permissions'][$role->name][$permission]) ? '#E6C2C1' : '#C1E6CD' ?>">
                <?= Html::checkbox(
                    $parentModel->formName() . '[permissions][' . $role->name . '][' . $permission . ']',
                    $model['permissions'][$role->name][$permission], [
                        'label' => null,
                        'uncheck' => 0,
                        'data' => [
                            'role' => $role->name,
                            'group' => $model['groupName']
                        ]
                    ]
                ) ?>
            </td>
        <?php endforeach; ?>
    </tr>
    <?php endforeach; ?>
</table>

rbac/views/default/index.php
<h1>Welcome to the RBAC Module</h1>
<?= \yii\bootstrap\Nav::widget([
    'items' => [
        ['label' => 'Assignment', 'url' => ['auth-assignment/index']],
        ['label' => 'Items', 'url' => ['auth-item/index']],
        ['label' => 'Item Children', 'url' => ['auth-item-child/index']],
        //['label' => 'Rules', 'url' => ['auth-rule/index']],
        ['label' => 'Permissions Table', 'url' => ['table']],
    ],
]) ?>

rbac/views/default/table.php
<?php

use kartik\grid\GridView;

$this->params['breadcrumbs'][] = ['url' => ['default/index'], 'label' => 'RBAC Module'];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php
/** @var \yii\widgets\ActiveForm $form */
$form = \yii\widgets\ActiveForm::begin();

$parentModel = $model;
$gridColumns = [
    [
        'class' => 'kartik\grid\DataColumn',
        'attribute' => 'groupName',
        'label' => Yii::$app->translate->t('Groups'),
        'vAlign' => 'middle',
    ],
    [
        'class' => 'kartik\grid\ExpandRowColumn',
        'detailRowCssClass' => GridView::TYPE_DEFAULT,
        'value' => function ($model, $key, $index, $column) {
            return GridView::ROW_COLLAPSED;
        },
        'detail' => function ($model, $key, $index, $column) use ($allRoles, $allPermissions, $parentModel) {
            return Yii::$app->controller->renderPartial('_tableDetails', [
                'model' => $model,
                'parentModel' => $parentModel,
                'allRoles' => $allRoles,
                'allPermissions' => $allPermissions,
            ]);
        },

    ],
];

echo GridView::widget([
    'dataProvider' => new \yii\data\ArrayDataProvider($model->getData()),
    'columns' => $gridColumns,
    'condensed' => true,
    'responsive' => true,
    'export' => false,
    'hover' => true,
]);

?>

<button type="submit" class="btn btn-success">Save</button>
<?php $form->end() ?>

<style>
    #permissions-table td:first-child{
        width: 200px;
    }
    #permissions-table .permission-description{
        font-size: 10px;
        font-family: Arial;
        font-style: oblique;
    }
</style>

<?php
$this->registerJs("
    var accessChangeColor = function(element) {
        element.closest('td').css('background-color', element.is(':checked') ? '#C1E6CD' : '#E6C2C1');
    }

    $('#permissions-table input[type=checkbox]').on('change', function(){
        accessChangeColor($(this));
    });

    $('input[type=checkbox].checker').on('change', function(){
        var
            role = $(this).data('role'),
            group = $(this).data('group'),
            checked = $(this).is(':checked'),
            elements = $('[data-role=' + role + ']').filter('[data-group=' + group + ']');

            elements.prop('checked', checked);
            elements.each(function(){
                accessChangeColor($(this));
            });
    });
")
?>